### ISSUE TITLE
BUG More than 5 log-in attempts

### ISSUE THREAD

**Issue by ElenaCherpakova** [JULIERAJ/KIDS-FIRST-Back#39]
Users can have login attempts 5 times but can do more than 5. we should notify the users of their 4th attempts and force them to change their password through forgot password section on their 5th time.

According to the acceptance criteria document:

Users have 5 attempts to log in; they can only fail login 4 times. Notify users that it is their last attempt
If the user fails their 5th attempt, they must make a new password. Direct users to the “forgot your password” procedure.

**Comment by JULIERAJ** [comment]
Closing issue. Was market as  ✅ Completed in [KIDS FIRST MVP 2024] project tracker.
