### ISSUE TITLE
Fix: style reset password email according to Figma

### ISSUE THREAD

**Issue by AnnaSolovykh** [JULIERAJ/KIDS-FIRST-Back#43]
**Requirements**
Update reset password template - use Figma design and existing template for password verification as a reference

![Image](https://github.com/user-attachments/assets/cab84fcb-e66c-4ac9-858e-902d078dd847)

![Image](https://github.com/user-attachments/assets/99dd3ab5-c6a4-4dc5-b441-ec35d89d85ec)

![Image](https://github.com/user-attachments/assets/1b6e794f-aa73-40d2-8477-4dcdf4febf20)

**Comment by JULIERAJ** [comment]
Closing issue. Was market as  ✅ Completed in [KIDS FIRST MVP 2024] project tracker.
