### ISSUE TITLE
Fix broken backend due to cloudinary configuration

### ISSUE THREAD

**Issue by nandini92** [JULIERAJ/KIDS-FIRST-Back#79]
Pipeline audit is failing which requires latest version of express to be installed:
![Image](https://github.com/user-attachments/assets/fe55a242-8f0f-4ff3-9aeb-0de1b5d415f9)

However, v5.0.0 is failing with the following error:
![Image](https://github.com/user-attachments/assets/eb2da1b6-96a1-4cd0-afc6-1774b70c8d22)

To fix this, Cloudinary config needs to be removed from app.js to only apply to specific routes.

**Comment by JULIERAJ** [comment]
Closing issue. Was market as  ✅ Completed in [KIDS FIRST MVP 2024] project tracker.
